export const FETCH_EVENT_TYPE_SUCCESSFUL = "FETCH_EVENT_TYPE_SUCCESSFUL";
export const FETCH_MONTHS_SUCCESSFUL = "FETCH_MONTHS_SUCCESSFUL";
export const FETCH_EVENTS_SUCCESSFUL = "FETCH_EVENTS_SUCCESSFUL";
export const APPLIED_FILTER_SUCCESSFUL = "APPLIED_FILTER_SUCCESSFUL";
export const START_LOADING="START_LOADING";
export const STOP_LOADING="STOP_LOADING";
export const SET_INITIAL_EVENT_TYPE_FILTER="SET_INITIAL_EVENT_TYPE_FILTER";
export const SET_INITIAL_EVENT_TYPE_MONTH="SET_INITIAL_EVENT_TYPE_MONTH";